/* scripted
    node {
	stage('Build') {
		echo "Build"
	}
	stage('Test') {
		echo "Test"
	}
	stage('Integration')
	{
		echo "Integration"
	}
}*/
//declarative 
pipeline {
	agent any
	stages{
		stage('Build'){
			steps{
				echo "Build"
			}
		}
		stage('Test'){
			steps{
				echo "Test"
			}
		}	
		stage("Integration testing")	{
			steps{
				echo "Integration steps"
			}
		}
	}post{
		always{
			echo  'I run always'
		}
		success{
			echo 'I run when I am successful'
		}
		failure {
			echo 'I run when you fail'
		}
	}

}
